recipes:
    mac_os_x:
        - osxdefaults::set_computer_name
attributes:
    osxdefaults:
        computername: Thiagos-MacBook-Pro.local
    homebrewalt:
        apps:
            - git-extras
        cask_apps:
            - sourcetree
