recipes:
    global:
        - applications::create_var_chef_cache
        - applications::mysql
    mac_os_x:
        - homebrewalt::default
        - applications::sublime_text_3
        - osxdefaults::finder_new_finder_windows_shows_homefolder
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::tap_to_click
attributes:
    mysql_root_password: root
    git:
        name: Thiago Leão Moreira
        email: tmoreira2020@gmail.com
    homebrewalt:
        apps:
            - ant
            - git
            - git-extras
            - gnupg
            - ImageMagick
            - jmeter
            - maven
            - npm
            - svn
            - tree
            - unrar
            - wget
            - zsh
            - zsh-completions
        cask_apps:
            - aqua-data-studio
            - dropbox
            - eclipse-jee
            - gimp
            - google-chrome
            - firefox
            - iterm2
            - java7
            - kindle
            - microsoft-office
            - picasa
            - rdio
            - send-to-kindle
            - skype
            - slack
            - sourcetree
            - vagrant
            - vagrant-manager
            - virtualbox
            - visualvm
            - yourkit-java-profiler
        cask_fonts:
            - inconsolata
    nodejs:
        apps:
            - gh
